### ISSUE TITLE
browser local storage

### ISSUE THREAD

**Issue by eramax** [da-z/llamazing#2]
Hi,

Please enable browser local storage, currently the chat(s) are disappeared after refreshing the browser. using https://my.llamaz.ing/

Best,

**Comment by da-z** [comment]
Hi. Yeah, that is somewhat by design. I personally never cared too much for previous messages. I'll think about it.

**Comment by da-z** [comment]
Fixed in [v0.6.5](https://github.com/da-z/llamazing/releases/tag/v0.6.5). Pushed to https://my.llamaz.ing/ as well.
