### ISSUE TITLE
Conversations history

### ISSUE THREAD

**Issue by eramax** [da-z/llamazing#3]
Thanks for supporting local storage,

I would like to ask if you are interested in enable conversations history like most of LLM UIs, so we can switch between conversations or start a new one while keeping all the conversations storied in the local cache.

Best,

**Comment by da-z** [comment]
No, that's useless for now. If I copy all features of other apps, there is no differentiating factor. I want to keep the code simple and extract as much functionality from it as possible.

For me, the next most important feature is to be able to upload a .doc or .pdf file and ask questions about it. But again, I don't want to bloat the frontend with that. I want the LLM service to support that (similar to vision). In this case, Ollama. Time will tell.

**Comment by da-z** [comment]
For now you can copy your conversations in Markdown format for pasting into some other editors, etc.

![img-VhMlTOcG](https://github.com/da-z/llamazing/assets/3681019/ffdc733a-a072-4f3f-914e-f2111dd5ea3f)
